# Generated by Django 5.2 on 2025-06-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='visa_type',
            field=models.CharField(choices=[('tourist', 'Tourist'), ('student', 'Student'), ('work', 'Work'), ('residence', 'Residence')], max_length=20),
        ),
    ]
